name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start
          browser: chrome
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_FAUCET_PK: ${{secrets.CYPRESS_FAUCET_PK}}
          REACT_APP_INFURA_ID: ${{secrets.REACT_APP_INFURA_ID}}


      - name: Save videos folder
        uses: actions/upload-artifact@v3
        with:
          name: videos
          if-no-files-found: error
          path: cypress/videos
